
services:
# Server / Backend
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 5000:5000
    environment:
      DB_HOST: mysql_db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: doc2_db
    depends_on:
      - mysql_db

# Frontend
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - server
# Database
  mysql_db:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: doc2_db